### ISSUE TITLE
是否可以不生成汇编代码直接运行呢？

### ISSUE THREAD

**Issue by Wenenen** [gitliuyuhan/compiler#3]
如题

**Comment by gitliuyuhan** [comment]
直接运行被编译的c代码么？

**Comment by gitliuyuhan** [comment]
@Wenenen 是直接运行被编译的c代码么？

**Comment by Wenenen** [comment]
是的，在程序中给出最终的运行结果。我看了项目中是生成了汇编，然后我想运行生成的汇编程序检验结果是否正确，但是没运行成功。所以想，把这部分也在程序中实现，而不是生成汇编代码。

**Comment by gitliuyuhan** [comment]
@Wenenen 明白你的意思了，因为最初的开发目标就只是把C代码编译成8086汇编代码，体验这个程序编译的过程。汇编代码可以手动在dosbox或emu8086上验证。
